import { AppShell } from "@mantine/core";
import Head from "next/head";
import React, { FC, ReactNode } from "react";

import { Header } from "./Header";

type Props = {
  children: ReactNode;
};

export const Layout: FC<Props> = ({ children }) => {
  return (
    <div>
      <Head>
        <title>my-recipe-search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell header={<Header />} fixed={false}>
        {children}
      </AppShell>
    </div>
  );
};
