import { NextPage } from "next";
import Head from "next/head";
import React from "react";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>my-recipe-search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <button className=" m-1 rounded border border-black bg-black p-2 text-xs text-white transition hover:bg-white hover:text-black hover:transition active:bg-gray-100">
          登録する
        </button>
        <button className=" m-1 rounded border border-black  bg-neutral-50    p-2 text-xs text-black transition hover:bg-white hover:text-black hover:transition active:bg-gray-100">
          登録する
        </button>
      </div>
    </div>
  );
};

export default Home;
